version: '3.8'

services:
  pulsopus-app:
    container_name: pulsopus-app
    build: .
    env_file:
      - .env
    ports:
      - '80:80'
    restart: always
    networks:
      - dev

networks:
  dev:
    driver: bridge
